import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const skill = fs.readFileSync(path.join(root, 'skills/jj-review/SKILL.md'), 'utf8')

test('jj-review finish reply is 客服 [OK]/[WARN]/[BLOCK] plus 修改意见', () => {
  assert.match(skill, /\[OK\]/)
  assert.match(skill, /\[WARN\]/)
  assert.match(skill, /\[BLOCK\]/)
  assert.match(skill, /一句总结/)
  assert.match(skill, /修改意见/)
  assert.match(skill, /STOP template on BLOCKED/)
  assert.doesNotMatch(skill, /same-turn/)
  assert.doesNotMatch(skill, /one-line on PASS/)
  assert.match(skill, /Wait for the user to say 「按审查改」/)
})

test('jj-review unbound when no ralph run; never init', () => {
  const host = fs.readFileSync(path.join(root, 'skills/jj-review/references/host-review.md'), 'utf8')
  assert.doesNotMatch(skill, /reason: no_ralph_run/)
  assert.match(skill, /Unspecified and no run → \*\*unbound\*\*; continue/)
  assert.match(skill, /Unbound review of working tree \/ HEAD/)
  assert.match(skill, /never init/i)
  assert.match(skill, /Explicit `run_id` named but missing/)
  assert.match(skill, /\*\*Persist\*\* — \*\*bound run only/)
  assert.match(host, /persist `REV-\*\.json` only when a ralph run is bound/)
  assert.match(host, /unbound\s+→ chat only/)
})

test('jj-review follow-up on same run is delta; no second full reviewer spawn', () => {
  const host = fs.readFileSync(path.join(root, 'skills/jj-review/references/host-review.md'), 'utf8')
  assert.match(skill, /G-review-1/)
  assert.match(skill, /G-review-5/)
  assert.match(skill, /resume_from/)
  assert.match(skill, /last completed `jj-reviewer`/)
  assert.match(skill, /Follow-up \/ delta/)
  assert.match(skill, /Do \*\*not\*\* spawn a fresh full-repo reviewer subagent/)
  assert.match(skill, /EP-20260907/)
  assert.match(skill, /Spawn a second full-repo reviewer subagent/)
  assert.match(host, /delta review/)
  assert.match(host, /must not be re-invoked/)
  assert.match(host, /Follow-up must not re-call `\/review`/)
})

test('jj-review parent is team-lead: spawn this turn, no startup reference dump', () => {
  assert.match(skill, /Parent is team-lead/)
  assert.match(skill, /spawn_subagent/)
  assert.match(skill, /jj-reviewer/)
  assert.match(skill, /派遣审查/)
  assert.match(skill, /派遣reviewer审查改动代码/)
  assert.match(skill, /description \*\*starts with\*\* `\[reviewer\]`/)
  assert.match(skill, /Do not wait silently/)
  assert.match(skill, /Before the spawn tool call/)
  assert.match(skill, /Do \*\*not\*\* perform the review in this chat/)
  assert.match(skill, /Do \*\*not\*\* re-read this SKILL/)
  assert.doesNotMatch(skill, /\]\(references\/report-layout\.md\)/)
  assert.doesNotMatch(skill, /\]\(references\/host-review\.md\)/)
  assert.doesNotMatch(skill, /\]\(references\/review-policy\.md\)/)
})

test('jj-reviewer pins reasoning_effort high, not inherit or xhigh', () => {
  const reviewer = fs.readFileSync(path.join(root, 'agents/jj-reviewer.md'), 'utf8')
  const implementer = fs.readFileSync(path.join(root, 'agents/jj-implementer.md'), 'utf8')
  const researcher = fs.readFileSync(path.join(root, 'agents/jj-researcher.md'), 'utf8')
  const host = fs.readFileSync(path.join(root, 'skills/jj-review/references/host-review.md'), 'utf8')
  assert.match(reviewer, /^reasoning_effort:\s*high\s*$/m)
  assert.doesNotMatch(reviewer, /xhigh/)
  assert.doesNotMatch(implementer, /reasoning_effort/)
  assert.doesNotMatch(researcher, /reasoning_effort/)
  assert.match(skill, /reasoning_effort: high/)
  assert.match(skill, /not inherit\/`xhigh`/)
  assert.match(host, /reasoning_effort: high/)
  assert.match(host, /not inherit\/`xhigh`/)
})

test('jj-review bound first review is exclusive assignment; no Grok /review dirty-tree', () => {
  const host = fs.readFileSync(path.join(root, 'skills/jj-review/references/host-review.md'), 'utf8')
  assert.match(skill, /G-review-2/)
  assert.match(skill, /exclusive input/)
  assert.match(skill, /task_paths/)
  assert.match(skill, /Do \*\*not\*\* invoke Grok `\/review`/)
  assert.match(skill, /\[reviewer\] local changes/)
  assert.match(skill, /当前的全部改动/)
  assert.match(skill, /客服 assignment/)
  assert.match(skill, /ASSIGNMENT-REVIEW/)
  assert.match(skill, /review-context\.json/)
  assert.match(skill, /Do \*\*not\*\* locate ralph/)
  assert.match(skill, /grep the whole repo/)
  assert.match(skill, /read jj-review\/jj-ralph SKILL/)
  assert.match(skill, /findings\.md/)
  assert.match(skill, /Read listed files then write findings/)
  assert.match(host, /exclusive/)
  assert.match(host, /task_paths/)
  assert.match(host, /must not call `\/review`/)
  assert.match(host, /Bound first/)
  assert.match(host, /G-review-2/)
  assert.match(host, /review-context\.json/)
  assert.match(host, /do not locate ralph/)
  assert.match(host, /do not grep the whole repo/)
  assert.match(host, /do not read jj-review\/jj-ralph SKILL/)
  assert.match(host, /Bound first never enters the host-callable `\/review` step/)
  assert.match(host, /ASSIGNMENT-REVIEW/)
  assert.match(skill, /never `\/review`/)
  assert.match(skill, /类型安全、null 处理、API 契约、回归/)
  assert.match(skill, /G-review-4/)
  assert.match(skill, /01a08fa6/)
  assert.match(skill, /审查还在跑/)
  assert.match(skill, /Start broad/)
  assert.match(host, /description \*\*starts with\*\* `\[reviewer\]`/)
  assert.match(host, /G-review-4/)
  assert.match(host, /never host \/review/)
  assert.match(host, /Do \*\*not\*\* call host `\/review`/)
  assert.match(host, /派遣审查/)
  assert.match(host, /派遣reviewer审查改动代码/)
})

test('jj-review conversational persist is documents not CLI; reply [BLOCK] first', () => {
  assert.match(skill, /G-review-3/)
  assert.match(skill, /01a08ea0/)
  assert.match(skill, /Conversational persist is \*\*documents\*\*, not CLI/)
  assert.match(skill, /Reply step 7 first/)
  assert.match(skill, /Never `review-record`/)
  assert.match(skill, /HIGH`→`high/)
  assert.match(skill, /本轮只有文案\/样式|copy\/CSS-only/)
  assert.match(skill, /accept_layers\.judgment/)
  assert.match(skill, /review\.reviews\[\]/)
  assert.match(skill, /review_scope=commit/)
  assert.doesNotMatch(skill, /Prefer CLI/)
  assert.doesNotMatch(skill, /review-report\.skeleton/)
  assert.doesNotMatch(skill, /\]\(references\/review-report\.skeleton\.json\)/)
  assert.doesNotMatch(skill, /archive needs a later `review-record/)
})

test('jj-review locates unspecified run from index.md 活跃 first', () => {
  const layout = fs.readFileSync(path.join(root, 'skills/jj-review/references/report-layout.md'), 'utf8')
  assert.match(skill, /index\.md/)
  assert.match(skill, /read `index\.md` \*\*活跃\*\* first/)
  assert.match(skill, /do not glob until that table is empty/)
  assert.match(skill, /else currently working from index\.md/)
  assert.match(layout, /currently working/)
  assert.match(layout, /## 活跃/)
  assert.match(layout, /\.workflow\/ralph\/index\.md` first/)
  assert.match(layout, /prefer status `IN_PROGRESS`/)
  assert.match(layout, /No 活跃 row \/ no `index\.md` → fallback glob/)
  assert.match(layout, /live `\.\workflow\/ralph\/<task_key>\/\.state\/run\.json`/)
  assert.doesNotMatch(layout, /pick latest among `\.\workflow\/ralph\/tasks\/\*\//)
})
