import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const skill = fs.readFileSync(path.join(root, 'skills/jj-same/SKILL.md'), 'utf8')
const assignment = fs.readFileSync(path.join(root, 'skills/jj-same/references/assignment.md'), 'utf8')
const onboarding = fs.readFileSync(path.join(root, 'skills/jj-same/references/onboarding.md'), 'utf8')
const happy = fs.readFileSync(path.join(root, 'skills/jj-same/references/happy-path.md'), 'utf8')

test('jj-same conversational path writes this-round assignment then researches then spawns', () => {
  assert.match(skill, /Parent chat is \*\*team-lead\*\*/)
  assert.match(skill, /Conversational path \(客服; must not skip\)/)
  assert.match(skill, /ASSIGNMENT-RESEARCH-<target>/)
  assert.match(skill, /ASSIGNMENT-HANDOFF-<target>/)
  assert.match(skill, /Call `spawn_subagent` \(`jj-researcher`; missing → `general-purpose`\) this turn/)
  assert.match(skill, /Spawn `jj-implementer` \(missing → `general-purpose`\)/)
  assert.match(skill, /派遣调研/)
  assert.match(skill, /派遣交接实施/)
  assert.match(skill, /description` starts `\[research\]`/)
  assert.match(skill, /description` starting `\[implementer\]`/)
  assert.match(skill, /G-same-2/)
  assert.match(skill, /G-same-3/)
  assert.match(skill, /resume_from/)
  assert.match(skill, /inherits cwd/)
  assert.match(skill, /01a08fa6/)
  assert.match(skill, /审查还在跑/)
  assert.match(skill, /Do not wait silently/)
  assert.match(skill, /Saying you will research without spawning fails/)
  assert.match(skill, /Do not `search_replace` in the parent/)
  assert.match(skill, /\*\*Do not\*\* port business code in this chat/)
  assert.match(skill, /\*\*Do not\*\* treat dispatch `distribution_prompt` as the worker spec or 入职/)
  assert.match(skill, /\*\*Do not\*\* open skill `references\/` from this entry/)
  assert.match(happy, /ASSIGNMENT-RESEARCH/)
  assert.match(happy, /ASSIGNMENT-HANDOFF/)
  assert.match(happy, /派遣调研/)
  assert.match(happy, /派遣交接实施/)
})

test('jj-same spawn includes 入职 prefix; assignment shapes stay off the SKILL entry', () => {
  assert.match(skill, /入职 prefix/)
  assert.match(skill, /调研 入职 prefix/)
  assert.match(skill, /实施 入职 prefix/)
  assert.match(skill, /never mix 调研\+实施/)
  assert.match(skill, /你不是 team-lead。你是目标仓调研工人/)
  assert.match(skill, /你不是 team-lead。你是目标仓实施工人/)
  assert.match(skill, /第一条回复必须是一句话确认/)
  assert.match(onboarding, /Spawn prefix（paste）/)
  assert.match(onboarding, /调研 Spawn prefix/)
  assert.match(onboarding, /实施 Spawn prefix/)
  assert.match(onboarding, /你不是 team-lead/)
  assert.doesNotMatch(skill, /调研：只读，不要改业务代码。实施：只改「交付」文件/)
  assert.match(onboarding, /不要 SendMessage/)
  assert.match(onboarding, /不要写 `\.plans\/daji-cs`/)
  assert.match(assignment, /exact paths/)
  assert.doesNotMatch(assignment, /先搜再读/)
  assert.match(assignment, /来自 team-lead/)
  assert.match(assignment, /请先一句话确认目标理解与第一步，再开工/)
  assert.match(assignment, /distribution_prompt` 是统筹索引，不是派单，也不是入职/)
  assert.doesNotMatch(skill, /\]\(references\/onboarding\.md\)/)
  assert.doesNotMatch(skill, /\]\(references\/assignment\.md\)/)
})

test('jj-same missing target Ralph writes documents, never init CLI', () => {
  const routing = fs.readFileSync(path.join(root, 'skills/jj-same/references/artifact-routing.md'), 'utf8')
  assert.match(skill, /Never `jj ralph init` CLI/)
  assert.match(routing, /Never `jj ralph init` CLI/)
  assert.doesNotMatch(routing, /\(`jj ralph init`\)/)
})

test('jj-same G-same-1 does not parent-port a stale DEL Goal', () => {
  assert.match(skill, /Golden Q&A — G-same-1/)
  assert.match(skill, /01a08e5b/)
  assert.match(skill, /d53a16510/)
  assert.match(skill, /识票同步验收/)
  assert.match(skill, /Parent `search_replace` in the target repos/)
  assert.match(skill, /Spawn with 入职 \+ `ASSIGNMENT-HANDOFF`/)
  assert.match(skill, /Empty `run\.handoff` after a landed sha is not a stop/)
})
