import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const skill = fs.readFileSync(path.join(root, 'skills/jj-same/SKILL.md'), 'utf8')
const assignment = fs.readFileSync(path.join(root, 'skills/jj-same/references/assignment.md'), 'utf8')
const onboarding = fs.readFileSync(path.join(root, 'skills/jj-same/references/onboarding.md'), 'utf8')
const happy = fs.readFileSync(path.join(root, 'skills/jj-same/references/happy-path.md'), 'utf8')
const spawn = fs.readFileSync(path.join(root, 'skills/jj/references/assignment-spawn.md'), 'utf8')

test('jj-same conversational path writes this-round assignment then researches then spawns', () => {
  assert.match(skill, /Parent chat is \*\*team-lead\*\*/)
  assert.match(skill, /Conversational path \(客服; must not skip\)/)
  assert.match(skill, /ASSIGNMENT-RESEARCH-<target>/)
  assert.match(skill, /ASSIGNMENT-HANDOFF-<target>/)
  assert.match(skill, /Call `spawn_subagent` \(`jj-researcher`; missing → `general-purpose`\) this turn/)
  assert.match(skill, /Spawn `jj-implementer` \(missing → `general-purpose`\)/)
  assert.match(skill, /assignment-spawn\.md/)
  assert.match(spawn, /派遣调研/)
  assert.match(spawn, /派遣交接实施/)
  assert.match(spawn, /\[research\]/)
  assert.match(spawn, /\[implementer\]/)
  assert.match(spawn, /description \*\*starts with\*\*/)
  assert.match(spawn, /resume_from/)
  assert.match(spawn, /inherits cwd/)
  assert.match(spawn, /Occupancy/)
  assert.match(spawn, /审查还在跑/)
  assert.match(spawn, /Do not wait silently/)
  assert.match(skill, /Do not `search_replace` in the parent/)
  assert.match(skill, /\*\*Do not\*\* port business code in this chat/)
  assert.match(skill, /\*\*Do not\*\* treat dispatch `distribution_prompt` as the worker spec or 人设提示词/)
  assert.doesNotMatch(skill, /## Happy path/)
  assert.match(skill, /Ralph-handoff-first/)
  assert.match(skill, /EXECUTION_READY/)
  assert.match(skill, /HANDOFF_READY/)
  assert.match(skill, /This skill's `references\/` are not a startup checklist/)
  assert.match(happy, /ASSIGNMENT-RESEARCH/)
  assert.match(happy, /ASSIGNMENT-HANDOFF/)
  assert.match(happy, /assignment-spawn\.md/)
})

test('jj-same spawn includes 人设提示词 prefix; assignment shapes stay off the SKILL entry', () => {
  assert.match(skill, /人设提示词 prefix/)
  assert.match(skill, /调研 人设提示词 prefix/)
  assert.match(skill, /实施 人设提示词 prefix/)
  assert.match(skill, /never mix 调研\+实施/)
  assert.match(skill, /你不是 team-lead。你是目标仓调研执行人/)
  assert.match(skill, /你不是 team-lead。你是目标仓实施执行人/)
  assert.match(skill, /第一条回复必须是一句话确认/)
  assert.match(onboarding, /Paste blocks live only in `skills\/jj-same\/SKILL\.md`/)
  assert.match(onboarding, /foreign team\/harness/)
  assert.doesNotMatch(onboarding, /调研 Spawn prefix/)
  assert.doesNotMatch(onboarding, /实施 Spawn prefix/)
  assert.doesNotMatch(onboarding, /不要 SendMessage/)
  assert.doesNotMatch(onboarding, /\.plans\/daji-cs/)
  assert.doesNotMatch(skill, /调研：只读，不要改业务代码。实施：只改「交付」文件/)
  assert.match(assignment, /exact paths/)
  assert.doesNotMatch(assignment, /先搜再读/)
  assert.match(assignment, /来自 team-lead/)
  assert.match(assignment, /请先一句话确认目标理解与第一步，再开工/)
  assert.match(assignment, /distribution_prompt` 是统筹索引，不是派单，也不是人设提示词/)
  assert.doesNotMatch(skill, /\]\(references\/onboarding\.md\)/)
  assert.doesNotMatch(skill, /\]\(references\/assignment\.md\)/)
})

test('jj-same write plane is the single home for init/ANL/ensureDispatch forbids', () => {
  const routing = fs.readFileSync(path.join(root, 'skills/jj-same/references/artifact-routing.md'), 'utf8')
  assert.match(skill, /## Write plane \(do not collapse\)/)
  assert.match(skill, /Never `jj ralph init` CLI/)
  assert.match(skill, /Do \*\*not\*\* call `ensureDispatchRalphRuns`/)
  assert.match(routing, /SKILL \*\*Write plane\*\*/)
  assert.doesNotMatch(routing, /Never `jj ralph init` CLI/)
  assert.doesNotMatch(routing, /same does \*\*not\*\* call `ensureDispatchRalphRuns`/)
  assert.match(happy, /SKILL \*\*Write plane\*\*/)
  assert.doesNotMatch(happy, /Do not call `ensureDispatchRalphRuns`/)
})

test('jj-same dual gates and closeout defer to happy-path', () => {
  assert.match(skill, /## Dual gates/)
  assert.match(skill, /happy-path\.md/)
  assert.doesNotMatch(skill, /## User-visible closeout/)
  assert.match(happy, /## User-visible closeout/)
  assert.match(happy, /## Dual gates/)
  assert.match(happy, /## Control-plane boundary/)
  assert.doesNotMatch(skill, /## Evidence entry points/)
  assert.doesNotMatch(skill, /## Artifact routing\n/)
})

test('jj-same user command page points at assignment-spawn, does not restate spawn protocol', () => {
  const userCmd = fs.readFileSync(path.join(root, 'docs/commands/jj-same.md'), 'utf8')
  assert.match(userCmd, /assignment-spawn\.md/)
  assert.doesNotMatch(userCmd, /派遣调研/)
  assert.doesNotMatch(userCmd, /派遣交接实施/)
  assert.doesNotMatch(userCmd, /审查还在跑/)
  assert.doesNotMatch(userCmd, /不要静默等待/)
})

test('jj-same Claude slash command points at assignment-spawn, does not restate spawn protocol', () => {
  const command = fs.readFileSync(path.join(root, 'claude-commands/jj-same.md'), 'utf8')
  assert.match(command, /assignment-spawn\.md/)
  assert.doesNotMatch(command, /派遣调研/)
  assert.doesNotMatch(command, /派遣交接实施/)
  assert.doesNotMatch(command, /不要静默等待/)
  assert.doesNotMatch(command, /G-same-3/)
})

test('jj-same does not parent-port a stale DEL Goal', () => {
  assert.doesNotMatch(skill, /Golden Q&A — G-same/)
  assert.doesNotMatch(skill, /01a08e5b/)
  assert.doesNotMatch(skill, /d53a16510/)
  assert.doesNotMatch(skill, /识票同步验收/)
  assert.match(skill, /Do not `search_replace` in the parent/)
  assert.match(skill, /Spawn with 人设提示词 \+ `ASSIGNMENT-HANDOFF`/)
  assert.match(skill, /Empty `run\.handoff` after a landed sha is not a stop/)
})
