#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

const requiredFiles = [
  'README.md',
  'ARCHITECTURE.md',
  'harness-manifest.json',
  'CHANGELOG.md',
  'release-please-config.json',
  '.release-please-manifest.json',
  '.github/workflows/ci.yml',
  '.github/workflows/harness-gardener.yml',
  '.github/workflows/pages.yml',
  '.github/workflows/release-please.yml',
  'bin/jj.mjs',
  'src/cli.mjs',
  'src/harnessDoctor.mjs',
  'src/harnessGc.mjs',
  'src/dispatch.mjs',
  'src/dispatchHostContract.mjs',
  'src/dispatchTrace.mjs',
  'src/handoffContract.mjs',
  'src/hostTrialRunner.mjs',
  'src/scenarioRunner.mjs',
  'src/recipes.mjs',
  'src/guards.mjs',
  'src/evidence.mjs',
  'src/evidenceProviders.mjs',
  'src/installSkill.mjs',
  'src/knowledgeLoop.mjs',
  'src/maestroCompatibility.mjs',
  'src/maestroExecution.mjs',
  'src/dispatchControlPlane.mjs',
  'src/taskRegistry.mjs',
  'scripts/build-docs.mjs',
  'scripts/check-harness.mjs',
  'tests/dispatch.test.mjs',
  'tests/task-registry.test.mjs',
  'tests/evidence.test.mjs',
  'tests/guards.test.mjs',
  'tests/install-skill.test.mjs',
  'tests/knowledge-loop.test.mjs',
  'tests/maestro-compatibility.test.mjs',
  'tests/maestro-execution.test.mjs',
  'tests/evidence-providers.test.mjs',
  'tests/fixtures/evidence-providers.json',
  'tests/harness-check.test.mjs',
  'tests/harness-doctor.test.mjs',
  'tests/harness-gc.test.mjs',
  'tests/host-trial.test.mjs',
  'tests/scenario-runner.test.mjs',
  'tests/jj-dispatch-contract.test.mjs',
  'tests/fixtures/dispatch-host-actions.json',
  'tests/fixtures/jj-dispatch-control-plane.json',
  '.codex/skills/jj/SKILL.md',
  '.codex/skills/jj-same/SKILL.md',
  '.codex/skills/jj-dispatch/SKILL.md',
  '.codex/skills/jj-dispatch/agents/openai.yaml',
  '.codex/agents/jj-workflow-reviewer.toml',
  '.codex/agents/jj-workflow-developer.toml',
  '.codex/skills/jj-dispatch/references/control-project.md',
  '.codex/skills/jj-dispatch/references/control-plane.schema.json',
  '.codex/skills/jj-dispatch/references/host-action-contract.json',
  '.codex/skills/jj-dispatch/references/host-action-contract.schema.json',
  '.codex/skills/jj-same/agents/openai.yaml',
  '.codex/skills/jj-same/references/continuous-sync.md',
  '.codex/skills/jj-same/references/handoff-snapshot.md',
  '.codex/skills/jj-same/references/handoff-snapshot.schema.json',
  '.codex/skills/jj-same/references/maestro-artifact-routing.md',
  '.codex/skills/jj-same/references/project-family.md',
  '.codex/skills/jj-same/references/silence-account-case.md',
  '.codex/skills/jj-same/scripts/collect-port-evidence.ps1',
  '.codex/skills/jj-same/scripts/extract_session_evidence.py',
  '.claude/commands/jj.md',
  '.claude/commands/jj-same.md',
  'workflows/jj-flow-ai-delivery.json',
  'examples/project-family-control/README.md',
  'examples/project-family-control/control-plane.json',
  'examples/scenarios/jj-same-handoff-snapshot.json',
  'docs/index.md',
  'docs/installation.md',
  'docs/project-plan.md',
  'docs/architecture.md',
  'docs/design-docs/index.md',
  'docs/design-docs/harness-engineering.md',
  'docs/exec-plans/index.md',
  'docs/exec-plans/active/2026-07-18-harness-hardening.md',
  'docs/adr/index.md',
  'docs/adr/0002-project-family-control-plane.md',
  'docs/commands.md',
  'docs/commands/jj.md',
  'docs/commands/jj-same.md',
  'docs/commands/jj-dispatch.md',
  'docs/commands/cli.md',
  'docs/glossary.md',
  'docs/usage.md',
  'docs/deployment.md',
  'docs/maintenance.md',
  'docs/milestones/m6-acceptance.md',
  'docs/milestones/m7-acceptance.md',
  'docs/milestones/m7-host-trial.json',
  'docs/milestones/h5-acceptance.md',
  'docs/milestones/h5-gc-baseline.json',
  'schemas/harness-manifest.schema.json',
  'schemas/dispatch-trace.schema.json',
  'schemas/host-trial-report.schema.json',
  'schemas/harness-gc-report.schema.json',
  'schemas/scenario-report.schema.json',
  'tests/docs-site.test.mjs'
];

const forbiddenFiles = [
  '.codex/skills/jj-delivery/SKILL.md',
  '.codex/skills/jj-validate/SKILL.md',
  '.codex/skills/jj-evolve/SKILL.md',
  '.claude/commands/jj-delivery.md',
  '.claude/commands/jj-validate.md',
  '.claude/commands/jj-evolve.md',
  'docs/commands/jj-delivery.md',
  'docs/commands/jj-validate.md',
  'docs/commands/jj-evolve.md',
  'src/projectEvolution.mjs',
  'src/projectValidation.mjs',
  'tests/project-validation.test.mjs',
  'tests/helpers/project-fixture.mjs'
];

const missing = requiredFiles.filter((file) => !fs.existsSync(path.join(process.cwd(), file)));
if (missing.length) {
  console.error(`Missing required files:\n${missing.map((file) => `- ${file}`).join('\n')}`);
  process.exit(1);
}

const stillPresent = forbiddenFiles.filter((file) => fs.existsSync(path.join(process.cwd(), file)));
if (stillPresent.length) {
  console.error(`Removed entry assets still present:\n${stillPresent.map((file) => `- ${file}`).join('\n')}`);
  process.exit(1);
}

console.log('project check passed');
