/** P1a façade: re-export split modules. CLI, tests, and ralph_ops keep importing ./ralph.mjs.
 * DAG: state ← gates ← map ← knowledge ← archive. Do not export * (unique is state-internal).
 */
export {
  ACCEPT_LAYER_STATUSES,
  FINDING_IMPORTANCE,
  FINDING_PASSES,
  GATE_ISSUE_CLASSES,
  HANDOFF_ROOT_REL,
  HOST_IDS,
  HOST_REVIEW_METHODS,
  INSTRUCTION_CORRECTION_REL,
  INTENSITY_DEFAULTS,
  JUDGMENT_MODES,
  RALPHS_DIR_REL,
  RALPH_ARCHIVE_DIR_REL,
  RALPH_TASKS_DIR_REL,
  STATE_REL,
  RALPH_HANDOFF_SCHEMA_VERSION,
  RALPH_INTENSITIES,
  RALPH_KNOWLEDGE_CONTRIBUTION_SCHEMA,
  RALPH_MAP_REL,
  RALPH_MAP_SCHEMA_VERSION,
  RALPH_REVIEW_SCHEMA_VERSION,
  RALPH_ROOT_REL,
  RALPH_RUN_SCHEMA_VERSION,
  RALPH_RUN_SCHEMA_VERSIONS,
  RALPH_RUN_SCHEMA_VERSION_1_1,
  RALPH_RUN_SCHEMA_VERSION_LEGACY,
  isLegacyRalphRunId,
  isTaskRunId,
  listRuns,
  locateRalphRuns,
  migrateHint,
  runStateDir,
  stripRunIdPrefix,
  TASK_PLAN_REL,
  FINDINGS_REL,
  PROGRESS_REL,
  GATE_SETS,
  SECTION_ACCEPT,
  SECTION_ANALYZE,
  SECTION_CURRENT,
  SECTION_FLAGGED,
  SECTION_GOAL,
  SECTION_LANDED,
  SECTION_MUST,
  SECTION_OPEN_QUESTIONS,
  SECTION_OUT,
  SECTION_PLAN,
  SECTION_SUPERSEDED,
  SECTION_UNRESOLVED,
  REVIEW_NIT_CAP,
  REVIEW_SCOPES,
  REVIEW_SOURCES,
  RUN_STATUSES,
  abandonRun,
  archiveDir,
  buildBudgetForIntensity,
  commitPrep,
  createEmptyAcceptLayers,
  createEmptyMap,
  createEmptyStagnation,
  createRunSkeleton,
  loadMap,
  loadRun,
  mapPath,
  normalizeHostMeta,
  normalizeIntensity,
  nowIso,
  ralphRoot,
  ralphsDir,
  readJson,
  recordHostMeta,
  renderRalphStatusText,
  runDir,
  runJsonPath,
  saveMap,
  saveRun,
  setRunStatus,
  suggestReopenAsNew,
  validateMap,
  validateReviewReport,
  validateRun,
  writeJson
} from './ralph/state.mjs';

export {
  FINDING_HINT,
  PHASE_ROLLBACK_EDGES,
  addGateIssue,
  applyHandoffState,
  buildPlanComplianceFindings,
  collectClaimedImplementationPaths,
  collectGitDeletedPaths,
  collectGitDiffPaths,
  computeRunMetrics,
  detectDeliverOutsideLedger,
  detectTestIntegrityViolation,
  evaluateAcceptArchiveGate,
  evaluateAcceptJudgment,
  extractLedgerPathRefs,
  extractMarkdownSection,
  extractPlanCurrentSection,
  readRunArtifactText,
  findImplementationPathMismatch,
  fingerprintDeliverState,
  getLatestReviewRecord,
  getStatus,
  inspectAcceptanceEvidence,
  isReviewSkipPath,
  isTestPath,
  persistRunMetrics,
  recordDeliverAttempt,
  resolveReviewScope,
  rollbackPhase,
  setAcceptLayer,
  setGate,
  writeDispatchSnapshot,
  writeHandoffPackage,
  writeInstructionCorrection
} from './ralph/gates.mjs';

export {
  buildElevationFromRun,
  capabilityFromRun,
  deriveAutoLessonsFromRun,
  findInMap,
  mapFind,
  mapMergeFromRun,
  mergeCapabilityIntoMap,
  tokenize
} from './ralph/map.mjs';

export {
  buildKnowledgeContribution,
  confirmProjectHotMemory,
  initRun,
  invokeKnowledgeContributeHook,
  KNOWLEDGE_CONTRIBUTION_DEGRADED_REASON,
  knowledgeContribute,
  normalizeHostReview,
  promoteHotMemoryFromRun,
  pruneProjectHotMemory,
  recordFinding,
  recordReview,
  resolveKnowledgeContributeHookConfig,
  resumeRun,
  writeKnowledgeContribution
} from './ralph/knowledge.mjs';

export {
  archiveRun,
  defaultArchiveDirName,
  finalizeRun
} from './ralph/archive.mjs';

export { loadNamingConfig, buildArchiveDirNameFromRunId, assertStrictRalphRunId, normalizeRalphSlug, buildRalphRunId } from './namingConfig.mjs';
export { adoptRun, migrateOneRun, migrateRuns, proposeTaskIdFromLegacy } from './ralph/migrate.mjs';
